module.exports = {
  CUST_TELEGRAM_BOT_TOKEN: process.env.CUST_TELEGRAM_BOT_TOKEN,
  ADMIN_TELEGRAM_BOT_TOKEN: process.env.ADMIN_TELEGRAM_BOT_TOKEN,
  BASE_URL: process.env.GAMEKU_API_URL,
  TV_BASE_URL: process.env.TV_BASE_URL,
  TV_MEMBER_CODE: process.env.TV_MEMBER_CODE,
  TV_SIGNATURE: process.env.TV_SIGNATURE,
  TV_SECRET_KEY: process.env.TV_SECRET_KEY,
};
